#!/bin/sh

. ~/.bin/misc/throw

echo

[[ -f ids.env ]] && currentUser="$(grep '^# User: ' ids.env | cut -d' ' -f3)" || currentUser=
currentUser="${currentUser:-$USER}"
read -p 'User: ' -i "$currentUser" -e user
userId=$(id -u "$user" 2> /dev/null)
[[ $? = 0 ]] || throw "$user: no such user"
homePath="$(eval echo "~$user")"
[[ -d "$homePath" ]] || throw "$user: home path does not exist"

[[ -f ids.env ]] && currentGroup="$(grep '^# Group: ' ids.env | cut -d' ' -f3)" || currentGroup=
currentGroup="${currentGroup:-$(id -gn "$user")}"
read -p 'Group: ' -i "$currentGroup" -e group
groupId=$(grep "^$group:" /etc/group | cut -d':' -f3)
[[ -z "$groupId" ]] && throw "$group: no such group"

echo
echo 'Writing ids.env...'
echo '# User / Group Identifiers' > ids.env
echo "# User: $user" >> ids.env
echo "PUID=$userId" >> ids.env
echo "# Group: $group" >> ids.env
echo "PGID=$groupId" >> ids.env
