version: "2.4"
services:

  jellyfin:
    # https://hub.docker.com/r/linuxserver/jellyfin
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    # mem_limit: 3g
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - tz.env
      - ids.env
    # environment:
    #   # Set the autodiscovery response domain or IP address.
    #   # - JELLYFIN_PublishedServerUrl=<hostIPAddress>
    ports:
      # HTTP webUI
      - 8096:8096
      # HTTPS webUI
      # - 8920:8920
      # Allows clients to discover Jellyfin on the local network
      - 7359:7359/udp
      # Service discovery used by DNLA and clients
      # - 1900:1900/udp
    volumes:
      - /var/services/homes/thomas/.docker/jellyfin:/config
      - /volume1/media/books:/data/books
      - /volume1/media/comics:/data/comics
      - /volume1/media/movies:/data/movies
      - /volume1/media/music:/data/music
      - /volume1/media/tvshows:/data/tvshows
    restart: unless-stopped
