version: "2.4"
services:

  jellyfin:
    # https://hub.docker.com/r/linuxserver/jellyfin
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    # mem_limit: 3g
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      # Set the autodiscovery response domain or IP address.
      # - JELLYFIN_PublishedServerUrl=<hostIPAddress>
    ports:
      # HTTP webUI
      - 8096:8096
      # HTTPS webUI
      # - 8920:8920
      # Allows clients to discover Jellyfin on the local network
      - 7359:7359/udp
      # Service discovery used by DNLA and clients
      # - 1900:1900/udp
    volumes:
      - $CONFIG/jellyfin:/config
      - $DATA/books:/data/books
      - $DATA/comics:/data/comics
      - $DATA/movies:/data/movies
      - $DATA/music:/data/music
      - $DATA/tvshows:/data/tvshows
    restart: unless-stopped
