#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"

if [[ ! -f docker-compose.yml ]]; then
	>&2 echo "File docker-compose.yml does not exist. Please run 'configure' first."
	exit 1
fi

sudo docker-compose pull
echo
sudo docker-compose up -d
