version: "2.4"
services:

  heimdall:
    # https://hub.docker.com/r/linuxserver/heimdall
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    ports:
      - 9080:80
      - 9443:443
    volumes:
      - $CONFIG/heimdall:/config
    restart: unless-stopped

  portainer:
    # https://hub.docker.com/r/portainer/portainer-ce
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG/portainer:/data
    restart: unless-stopped

  sslh:
    # https://github.com/yrutschle/sslh
    build: ./sslh
    image: sslh
    container_name: sslh
    hostname: sslh
    network_mode: host
    command: --listen $SSLH_HOST:$SSLH_PORT --ssh $SSLH_SSH_HOST:$SSLH_SSH_PORT --tls $SSLH_HTTPS_HOST:$SSLH_HTTPS_PORT -v
    restart: unless-stopped

  wireguard:
    # https://hub.docker.com/r/linuxserver/wireguard
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVERURL=$WIREGUARD_URL
      - SERVERPORT=$WIREGUARD_PORT
      - PEERS=$WIREGUARD_PEERS
      - PEERDNS=$WIREGUARD_PEERDNS
      - INTERNAL_SUBNET=$WIREGUARD_SUBNET
      - ALLOWEDIPS=$WIREGUARD_ALLOWEDIPS
      - PERSISTENTKEEPALIVE_PEERS=
      - LOG_CONFS=true
    ports:
      - 51820:51820/udp
    volumes:
      - $CONFIG/wireguard:/config
    restart: unless-stopped
