version: '3'
services:

  sslh:
    # https://hub.docker.com/r/oorabona/sslh/
    image: oorabona/sslh
    container_name: sslh
    hostname: sslh
    env_file:
      - sslh.env
    ports:
      - '44322:443'
    command:
      - -f
