version: "2.4"
services:

  heimdall:
    # https://hub.docker.com/r/linuxserver/heimdall
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $CONFIG/heimdall:/config
    ports:
      - 9080:80
      - 9443:443
    restart: unless-stopped

  portainer:
    # https://hub.docker.com/r/portainer/portainer-ce
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG/portainer:/data
    restart: unless-stopped

  sslh:
    # https://github.com/yrutschle/sslh
    build: ./sslh
    image: sslh
    container_name: sslh
    hostname: sslh
    network_mode: host
    command: --listen $SSLH_HOST:$SSLH_PORT --ssh $SSLH_SSH_HOST:$SSLH_SSH_PORT --tls $SSLH_HTTPS_HOST:$SSLH_HTTPS_PORT -v
    restart: unless-stopped
