version: "2.4"
services:

  homepage:
    # https://github.com/gethomepage/homepage/pkgs/container/homepage
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    hostname: homepage
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # For docker integrations
      - $CONFIG/homepage:/app/config # Make sure your local config directory exists
    restart: unless-stopped

  portainer:
    # https://hub.docker.com/r/portainer/portainer-ce
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFIG/portainer:/data
    restart: unless-stopped

  # sslh:
  #   # https://github.com/yrutschle/sslh
  #   build: ./sslh
  #   image: sslh
  #   container_name: sslh
  #   hostname: sslh
  #   network_mode: host
  #   command: --listen $SSLH_HOST:$SSLH_PORT --ssh $SSLH_SSH_HOST:$SSLH_SSH_PORT --tls $SSLH_HTTPS_HOST:$SSLH_HTTPS_PORT -v
  #   restart: unless-stopped

  # wireguard:
  #   # https://hub.docker.com/r/linuxserver/wireguard
  #   image: linuxserver/wireguard
  #   container_name: wireguard
  #   hostname: wireguard
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=$PUID
  #     - PGID=$PGID
  #     - TZ=$TZ
  #     - SERVERURL=$WIREGUARD_URL
  #     - SERVERPORT=$WIREGUARD_PORT
  #     - PEERS=$WIREGUARD_PEERS
  #     - PEERDNS=$WIREGUARD_PEERDNS
  #     - INTERNAL_SUBNET=$WIREGUARD_SUBNET
  #     - ALLOWEDIPS=$WIREGUARD_ALLOWEDIPS
  #     - PERSISTENTKEEPALIVE_PEERS=
  #     - LOG_CONFS=true
  #   ports:
  #     - 51820:51820/udp
  #   volumes:
  #     - $CONFIG/wireguard:/config
  #   restart: unless-stopped
