#!/bin/sh
name="$1" service="$2"

cd "$(realpath "$0" | xargs dirname)"
. misc/throw

[ -z "$name" ] && throw 'name expected'
[ -d "../$name" ] || throw "$name: directory not found"
cd "../$name"

[ -f docker-compose.yml ] || throw "docker-compose.yml does not exist, run 'configure' script first"

which docker-compose > /dev/null || throw 'docker-compose: command not found'

sudo docker-compose pull $service
echo
sudo docker-compose build --pull $service
echo
sudo docker-compose up -d $service
