#!/bin/sh
path="$(readlink -f "$1")" && shift && args="$@"
# e.g. -Debug -WhatIf

cd "$(dirname "$(readlink -f "$0")")"
. misc/throw

[ -z "$path" ] && throw 'path expected'
[ -d "$path" ] || throw "$path: directory not found"

mkdir -p "$PWD/../.cache"
[ -f "$PWD/../.cache/fix-srt.json" ] || touch "$PWD/../.cache/fix-srt.json"

sudo docker run -it --rm \
  -e POWERSHELL_TELEMETRY_OPTOUT=1 \
  -v "$PWD:/mnt/bin" \
  -v "$PWD/../.cache:/mnt/cache" \
  -v "$path:$path" \
  mcr.microsoft.com/powershell \
  pwsh -File /mnt/bin/fix-srt.ps1 -Path "$path" -Cache /mnt/cache/fix-srt.json $args
