#!/bin/sh

_home="$1"
_user="$2"

# Remove @eaDir directories
find "$_home" -depth -name '@eaDir' -type d -exec rm -rf '{}' \;
find '/volume1/media' -depth -name '@eaDir' -type d -exec rm -rf '{}' \;

# Reset home default permissions
chown -R "$_user:users" "$_home"
synoacltool -copy "$_home/.." "$_home"
synoacltool -del "$_home"
synoacltool -add "$_home" 'user:root:allow:rwxpdDaARWcCo:---n'
synoacltool -add "$_home" "user:$_user:allow:rwxpdDaARWcCo:fd--"

# Enforce home permissions (skipping .media directory if any)
find "$_home" -mindepth 1 \( -path "$_home/.media" -type d -prune -o -type d -exec synoacltool -enforce-inherit '{}' \; \)
find "$_home" -path "$_home/.media" -type d -prune -o -not -type d -exec synoacltool -enforce-inherit '{}' \;

# Set right permissions on .ssh directory if any in order to allow SSH keys authentication
if [[ -d "$_home/.ssh" ]]; then
    chmod 755 "$_home"
    chmod -R a-x,u=rwX,go=rX "$_home/.ssh"
    [[ -f "$_home/.ssh/authorized_keys" ]] && chmod go-r "$_home/.ssh/authorized_keys"
    [[ -f "$_home/.ssh/id_rsa" ]] && chmod go-r "$_home/.ssh/id_rsa"
    [[ -f "$_home/.ssh/id_rsa.ppk" ]] && chmod go-r "$_home/.ssh/id_rsa.ppk"
fi

# Set right permissions on .media directory if any
if [[ -d "$_home/.media" ]]; then
    chmod -R a-x,u=rwX,go=rX "$_home/.media"
    [[ -d "$_home/.media/plex/Library" ]] && chown root:root "$_home/.media/plex/Library"
fi
