#!/bin/sh
path="$1"

cd "$(dirname "$(readlink -f "$0")")"
. misc/throw

[[ -z "$path" ]] && throw 'path expected'
[[ -d "$path" ]] || throw "$path: directory not found"

sudo docker run -it --rm -e POWERSHELL_TELEMETRY_OPTOUT=1 -v "$PWD:/mnt/bin" -v "$path:/data" mcr.microsoft.com/powershell pwsh -File /mnt/bin/fix-srt.ps1 -Path /data
# -Debug -WhatIf
